language: python
sudo: required
python:
- '3.4'
before_install:
- sudo apt-get install -y tree
- sudo apt-get install -y rpm
- sudo apt-get install -y alien
- sudo apt-get install -y python3-gi
- sudo apt-get install -y python3-gi-cairo
- sudo apt-get install -y gir1.2-gtk-3.0
- sudo apt-get install -y gir1.2-poppler-0.18
- sudo apt-get install -y fakeroot
install:
- sudo pip install pyinstaller
- sudo pip install pysftp
- whereis pyinstaller
script:
- nosetests
- python build.py
- ls
- cd dist
- ls
deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  api_key:
    secure: pxqF0sLkmvkWy+EzC4brEzAnmP1hCnyLv/UgleSiZomURfRfudR6nGFAiVjvAf5tWpKQdmsbaxqo1C3rajMqlrgw2TXs93wVPF3IsmBrs2qKzXbq92g/C19o7/kgk9NlA6vs/S2KL60aBe9WR46rKKbo9gaUM4heYcZqwaXfq4tSTI8cwHmMaZ8wIY2va4J4rxptjHlIvApuRhFHzG7ng4Mmh8mJBDKoevOmT3R6PdO626CooCRtnZHBs3hfqHGSxGlCHPMMaEFJI1MXvYtWaP6zOlOePoxjBWKFk1hP+IPvb65/K8/iUZQ7FK+X+KQuHe0pyieO4QMSqKiVlJgXM4SXSNm+VGbmqXDXyBhoesU6jr6TWUTPTB2ZF5QFPTGgUyV14GrlAxRkWRMsk4BN/vJMIts2fuz6niVbXUSTA5yj6IKcLhflsmzC7j6Z8QjCdv9y6wGKtSzDqWtQUuIPbT5AJNCfEIjwNSFWzEyhhv06crILZFt12moGchtXkIegfy1ymOTr8Mvd8PidIoYsXJnUuBr2+dxfHFRphmZMd4afg0jWBWQRFGnmkR1RKQPPxh+VcZAAMZ9DncTK4xsRk7pcMJ8r7jMHXXBe02yXRLpJGq8uGZwgyjxtRkZV8jJeEqAd/pcwEuAJFnWSqDDeUpOHnIS5w4oL2xwGppgQR08=
  file:
    - "dist/*.rpm"
    - "dist/*.tar.gz"
    - "dist/*.deb"
  file_glob: true
  on:
    tags: false
    repo: Averell7/PdfBooklet
