language: python

sudo: required
python:
  - "2.7"
  - "3.4"
before_install:  
  - sudo apt-get install -y rpm

    

  
install: 
  - pip install flake8 tox  

script: 
  - nosetests 
  - cat toto

  