language: python

sudo: required
python:
#  - "2.7"
  - "3.5"
before_install:  
  - sudo apt-get install -y rpm
  - sudo apt-get install -y python-gi 
#  - sudo apt-get install -y python3-gi
  - sudo apt-get install -y gir1.2-gtk-3.0
  - sudo apt-get install -y gir1.2-poppler-0.18
    
  - sudo ls /home/travis/virtualenv/python3.5.2/lib/python3.5
  
install: 
  - pip install flake8 tox  
  - pip install pyinstaller

script: 
  - nosetests 
#  - sudo pyinstaller ./pdfbooklet/pdfbooklet.py
  - sudo python build.py

  